# Generated by Django 5.0.3 on 2024-05-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_amenity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
