# Generated by Django 5.0.3 on 2024-05-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_remove_perk_category_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
