# Generated by Django 5.0.3 on 2024-05-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='experience_tie',
            new_name='experience_time',
        ),
    ]
